"""Aggregate published conformance reports into spec-repo conformance files.

Each implementation that publishes a machine-readable conformance report — a
deterministic JSON projection of its own conformance mapping — is fetched and
transformed into conformance/<impl>.yaml. This retires hand-authoring those
files: the implementation's own mapping is the single source of truth, and the
spec repo *aggregates* the published reports rather than duplicating their
status (CKSPEC SSOT / feedback cycle).

Implementations that do NOT yet publish a report are left untouched (graceful
fallback) — their conformance/<impl>.yaml stays hand-authored until they adopt
the published-report pattern.

The published report intentionally carries no timestamp (so the implementation's
sync-check is stable); the aggregator stamps the fetch date as report_date here.
"""

import argparse
import datetime
import json
import os
import sys
import urllib.error
import urllib.request

import yaml

# Registry: implementations that publish a machine-readable conformance report.
# An implementation absent from this map keeps its hand-authored
# conformance/<impl>.yaml (graceful fallback until it adopts the pattern).
PUBLISHED_REPORTS = {
    "ckeletin-go": (
        "https://raw.githubusercontent.com/peiman/ckeletin-go/main/conformance-report.json"
    ),
}


def fetch_report(source, timeout=10):
    """Fetch and parse a published conformance report (JSON).

    ``source`` is an http(s) URL or a local file path (the latter for tests).
    """
    if "://" in source:
        with urllib.request.urlopen(source, timeout=timeout) as resp:  # noqa: S310
            return json.loads(resp.read().decode("utf-8"))
    with open(source, "r") as f:
        return json.load(f)


def report_to_conformance(report, report_date):
    """Transform a published report dict into the spec-repo conformance shape.

    Output matches what scripts/validate_spec.py requires: a header with
    implementation/spec_version/report_date and a requirements map where each
    entry has at least status + evidence.
    """
    requirements = {}
    for req_id in sorted(report.get("requirements", {})):
        entry = report["requirements"][req_id]
        out = {
            "status": entry["status"],
            "evidence": (entry.get("evidence") or "").strip(),
        }
        if entry.get("enforcement_level"):
            out["enforcement_level"] = entry["enforcement_level"]
        if entry.get("checks"):
            out["tests"] = list(entry["checks"])
        if entry.get("violation_tests"):
            out["violation_tests"] = list(entry["violation_tests"])
        violation_evidence = (entry.get("violation_evidence") or "").strip()
        if violation_evidence:
            out["violation_evidence"] = violation_evidence
        requirements[req_id] = out

    return {
        "implementation": report["implementation"],
        "spec_version": report["spec_version"],
        "report_date": report_date,
        "requirements": requirements,
    }


def _str_representer(dumper, data):
    """Render multi-line strings as literal block scalars for readability."""
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


class _ConformanceDumper(yaml.SafeDumper):
    """Private dumper so the str representer never mutates the global SafeDumper."""


_ConformanceDumper.add_representer(str, _str_representer)


def dump_conformance_yaml(data):
    """Serialize a conformance dict to YAML (deterministic, insertion order)."""
    return yaml.dump(
        data,
        Dumper=_ConformanceDumper,
        default_flow_style=False,
        sort_keys=False,
        allow_unicode=True,
        width=88,
    )


def write_conformance_file(path, data):
    """Write conformance/<impl>.yaml with an auto-generated header banner."""
    banner = (
        f"# {os.path.basename(path)}\n"
        f"# Conformance report for {data['implementation']} against the ckeletin spec.\n"
        "#\n"
        "# AUTO-GENERATED by scripts/aggregate_conformance.py from the implementation's\n"
        "# published conformance-report.json. Do NOT edit by hand — run\n"
        "# 'task generate:conformance' to refresh.\n\n"
    )
    # Build the full content BEFORE opening the file, so a serialization error
    # cannot truncate the existing report (graceful fallback).
    content = banner + dump_conformance_yaml(data)
    with open(path, "w") as f:
        f.write(content)


def aggregate(conformance_dir, report_date, only_impl=None, registry=None):
    """Refresh conformance/<impl>.yaml for every registered implementation.

    Returns (written, failed) lists of implementation names. A fetch failure
    leaves the existing file untouched (graceful fallback).
    """
    registry = PUBLISHED_REPORTS if registry is None else registry
    written, failed = [], []
    for impl, source in registry.items():
        if only_impl and impl != only_impl:
            continue
        # Fetch, transform, and write are all guarded: a fetch failure OR a
        # structurally malformed report (missing keys, wrong types) leaves the
        # existing conformance/<impl>.yaml untouched and does not abort the run
        # for the other implementations (graceful per-impl fallback).
        try:
            report = fetch_report(source)
            data = report_to_conformance(report, report_date)
            out_path = os.path.join(conformance_dir, f"{impl}.yaml")
            write_conformance_file(out_path, data)
        except (
            urllib.error.URLError, OSError, ValueError, KeyError, TypeError, AttributeError
        ) as exc:
            print(
                f"⚠ {impl}: could not process report ({exc}); "
                f"leaving conformance/{impl}.yaml unchanged"
            )
            failed.append(impl)
            continue
        print(
            f"✓ {impl}: wrote {os.path.relpath(out_path)} "
            f"({len(data['requirements'])} requirements, spec {data['spec_version']})"
        )
        written.append(impl)
    return written, failed


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--date",
        default=None,
        help="report_date to stamp (default: today, ISO 8601)",
    )
    parser.add_argument(
        "--impl",
        default=None,
        help="aggregate only this implementation (default: all registered)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit non-zero if any registered report could not be fetched",
    )
    args = parser.parse_args()

    report_date = args.date or datetime.date.today().isoformat()
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    conformance_dir = os.path.join(repo_root, "conformance")

    written, failed = aggregate(conformance_dir, report_date, only_impl=args.impl)

    print()
    print(f"Aggregated {len(written)} report(s); {len(failed)} could not be refreshed.")
    if failed and args.strict:
        sys.exit(1)


if __name__ == "__main__":
    main()
